### ISSUE TITLE
Python time format error

### ISSUE THREAD

**Issue by snackysm0res** [hRun/SA-haveibeenpwned#12]
The "haveibeenpwned" command started throwing this error today:

`ValueError at "/opt/splunk/lib/python3.7/_strptime.py", line 359 : time data '2019-01-16T21:46:07.1' does not match format '%Y-%m-%dT%H:%M:%SZ'`

![image](https://github.com/user-attachments/assets/82886bf1-3bdf-42f9-8bdb-9f5c57924704)

There haven't been any known changes on my end that would have caused this. I'm running the latest version of the add on (2.2.7) on Splunk Cloud version 9.1.2312.205.

**Comment by hRun** [comment]
this looks to me like there might be new records being returned from hibp with an incorrect/new/changed time format. the hibp api documentation doesn't mention a changed time format, so i assume it's a mistake. hibp might have noticed this on their end as well, did the issue resolve itself in the meantime? 

nonetheless, i'll try to find time on friday to implement a check for different time formats in the app. it'll take some time until it will be available on splunkbase, as unfortunately splunk always takes a long time to review and approve apps for the cloud.

**Comment by snackysm0res** [comment]
I retested, and it's working now. Looks like it resolved itself. 

Thank you for the quick response!
